---

- name: Install Gitlab repository key
  apt_key:
    url: https://packages.gitlab.com/runner/{{ gitlab_runner_package_name }}/gpgkey
    state: present

- name: Fetch the apt configuration
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/{{ gitlab_runner_package_name }}/config_file.list?os={{ansible_distribution}}&dist={{ansible_distribution_release}}&source=script
    dest: /etc/apt/sources.list.d/runner_{{ gitlab_runner_package_name }}.list
    mode: 0644

- name: (Debian) Install GitLab Runner
  apt:
    name: "{{ gitlab_runner_package_name }}{{ ('=' + gitlab_runner_package_version) if gitlab_runner_package_version is defined else '' }}"
    state: "{{ 'present' if gitlab_runner_package_version is defined else 'latest' }}"
